name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  fides_checks:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sample_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      # For the purposes of this example, we are hosting a Fides Server in this CI job
      # In a production environment, this service would not be here and an end user would point 
      # the Fides Scan and Fides evaluate commands to a production instance hosted elsewhere. 
      postgresfides:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fides
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
      
      fides:
        image: ethyca/fides
        env:
          FIDES__DATABASE__SERVER: postgresfides
          FIDES__DATABASE__USER: postgres
          FIDES__DATABASE__PASSWORD: postgres
          FIDES__DATABASE__PORT: 5433
          FIDES__DATABASE__DB: fides
          FIDES__SECURITY__APP_ENCRYPTION_KEY: OLMkv91j8DHiDAULnK5Lxx3kSCov30b3
          FIDES__SECURITY__OAUTH_ROOT_CLIENT_ID: cicdclient
          FIDES__SECURITY__OAUTH_ROOT_CLIENT_SECRET: cicdsecret
        ports:
          - 8080:8080
        options: --health-cmd "curl --fail http://localhost:8080/health || exit 1" --health-interval 10s --health-timeout 10s --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install psycopg2-binary ethyca-fides
      - name: Run database migrations
        run: |
          python -c "
          import os
          import psycopg2
          from psycopg2 import sql

          DB_HOST = 'localhost'
          DB_PORT = 5432
          DB_USER = 'postgres'
          DB_PASSWORD = 'postgres'
          DB_NAME = 'sample_db'

          conn = psycopg2.connect(
              dbname=DB_NAME,
              user=DB_USER,
              password=DB_PASSWORD,
              host=DB_HOST,
              port=DB_PORT
          )

          with open('database/migrations/postgres_sample.sql', 'r') as f:
              sql_script = f.read()

          with conn.cursor() as cursor:
              cursor.execute(sql_script)
              conn.commit()

          conn.close()
          "
      - name: Scan Database and validate that all fields are accounted for
        run: fides scan dataset db --connection-string postgres://postgres:postgres@localhost:5432/postgres_example
      - name: Evaluation
        run: fides evaluate .fides/
